version: "3.9"
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - sheshu-db:/var/lib/postgresql/data
      - ./create-table.sql:/docker-entrypoint-initdb.d/create_tables.sql


  nodejs:
    image: sheshuvalandas/employe
    container_name: nodejs
    networks:
      - webnet
    ports:
      - "4000:4000"

    environment:
      DB_HOST: postgres-db
      DB_USER: postgres
      DB_PORT: 5432
      DB_PASSWORD: 12345
      DB_SCHEMA: postgres
     # connectionString: postgres://postgres:12345@postgres-db:5432/sheshu
      #- ConnectionStrings_DefaultConnection=Server=postgres-db;database=postgres;User Id=postgres;Password=12345

    depends_on:
      - postgres-db

networks:
  webnet:

volumes:
  sheshu-db:






