version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sheshu
    volumes:
      - sheshu-db:/var/lib/postgresql/data


  nodejs:
    image: sheshuvalandas/project
    container_name: nodejs
    ports:
      - "4000:4000"

    environment:
      - 'connectionString:postgres://postgres:12345@db:5432/sheshu'
      PORT: 4000
    depends_on:
      - db
    links:
      - "db:database"

volumes:
  sheshu-db:






