version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - webnet
      #ports:
     # - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sheshu
    volumes:
      - sheshu-db:/var/lib/postgresql/data
      - ./create-table.sql:/docker-entrypoint-initdb.d/create_tables.sql


  nodejs:
    image: sheshuvalandas/project
    container_name: nodejs
    networks:
      - webnet
    ports:
      - "4000:4000"
    environment:

      - connectionString=Server=db,5432;database=sheshu;User Id=postgres;Password=12345
    depends_on:
      - db
    links:
      - db
networks:
  webnet:

volumes:
  sheshu-db:






