version: "3.9"
services:
  nodejs:
    image: sheshuvalandas/project
    container_name: nodejs
    ports:
      - 80:4000

    environment:
      connectionString: postgres://postgres:12345@db:5432/sheshu
      PORT: 4000

    depends_on:
      - postgres

    links:
      - postgres

  db:
    image: postgres:9.3
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sheshu




