version: "3.9"
services:
  nodejs:
    image: sheshuvalandas/project
    container_name: nodejs
    ports:
    - "80:4000"
    depends_on:
    - postgres
    environment:
      - DATABASE_URL=postgres://postgres:12345@db:5432/sheshu
      - PORT=4000

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=sheshu



