version: "3.9"
services:
  nodejs:
    image: sheshuvalandas/employe
    container_name: nodejs
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres-db:5432/sheshu
    ports:
      - "4000:4000"

    command: node app.js
    volumes:
      - .:/app/
      - /app/postgres/node_modules

  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sheshu
    volumes:
      - ./create-table.sql:/docker-entrypoint-initdb.d/create_tables.sql











