version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      PSQL_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sheshu
    volumes:
      - sheshu-db:/var/lib/postgresql/data
      - ./create-table.sql:/docker-entrypoint-initdb.d/create_tables.sql


  nodejs:
    image: sheshuvalandas/project
    container_name: nodejs
    ports:
      - "4000:4000"

    environment:
      connectionString: db
      #- connectionString=Server=localhost,5432;database=sheshu;User Id=postgres;Password=12345
    depends_on:
      - db
    links:
      - db

volumes:
  sheshu-db:






