version: "3.9"
services:
  postgres:
    image: postgres:latest

  nodejs:
    build:
      context: .
    container_name: nodejs
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - .:/app # Look at the server directory and copy everything into the app folder in the container
      - ./create-table.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      ##DATABASE_URL: "postgres://postgres:12345@postgres:5432/sheshu"
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=sheshu
      - PGPASSWORD=12345
      - PGPORT=5432
    ports:
      - "4000:4000"














