version: "3.9"
services:
  nodejs:
    image: sheshuvalandas/employe
    container_name: nodejs
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/sheshu
      PORT: 4000
    ports:
      - "4000:4000"

  postgres:
    image: postgres:10.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sheshu
    volumes:
      - ./create-table.sql:/docker-entrypoint-initdb.d/create_tables.sql











